import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#1e40af",
        secondary: "#fbbf24",
        "background-light": "#f8fafc",
        "background-dark": "#0f172a",
        kashmir: {
          blue: "#1A3A6B",
          bright: "#0F5FD7",
          gold: "#C89B3C",
          teal: "#2A7F7F",
          cream: "#F8F7F2",
          charcoal: "#1C1C1E",
          slate: "#6B7280",
          green: "#16A34A",
          crimson: "#DC2626",
        },
        "on-secondary-fixed": "#261900",
        "surface-container-highest": "#e3e2e7",
        "error": "#ba1a1a",
        "tertiary-fixed": "#a1f0f0",
        "surface-container-high": "#e9e7ec",
        "on-secondary-container": "#755400",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdea4",
        "surface-variant": "#e3e2e7",
        "tertiary-container": "#004242",
        "tertiary": "#002a2a",
        "surface-container": "#eeedf2",
        "on-tertiary-fixed": "#002020",
        "surface-tint": "#415e91",
        "on-tertiary-fixed-variant": "#004f50",
        "on-primary": "#ffffff",
        "on-surface-variant": "#43474f",
        "outline": "#747780",
        "inverse-surface": "#2f3034",
        "outline-variant": "#c4c6d0",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#85d4d3",
        "primary-fixed-dim": "#abc7ff",
        "background": "#faf9fe",
        "secondary-fixed-dim": "#f0bf5c",
        "on-primary-fixed": "#001b3f",
        "surface": "#faf9fe",
        "primary-fixed": "#d7e2ff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf9fe",
        "inverse-primary": "#abc7ff",
        "on-background": "#1a1b1f",
        "on-primary-container": "#89a5dd",
        "on-secondary-fixed-variant": "#5d4200",
        "surface-dim": "#dad9de",
        "secondary-container": "#fcca66",
        "inverse-on-surface": "#f1f0f5",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f4f3f8",
        "error-container": "#ffdad6",
        "on-surface": "#1a1b1f",
        "on-tertiary-container": "#62b1b1",
        "primary-container": "#1a3a6b",
        "on-primary-fixed-variant": "#284678"
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        serif: ["DM Serif Display", "serif"],
        sans: ["Source Sans Pro", "sans-serif"],
        numbers: ["Space Grotesk", "sans-serif"],
        amiri: ["Amiri", "serif"],
        aalto: ["Aalto", "sans-serif"],
        varien: ["Varien", "sans-serif"],
      },
      boxShadow: {
        travel: "0 18px 45px rgba(26, 58, 107, 0.14)",
      },
    },
  },
  plugins: [],
} satisfies Config;
